import jsPDF from 'jspdf'
import { FortuneResult } from '../types'

export function generatePDF(result: FortuneResult) {
  const pdf = new jsPDF()
  
  const pageWidth = pdf.internal.pageSize.getWidth()
  const margin = 20
  let yPos = 20

  pdf.setFontSize(24)
  pdf.setTextColor(0, 240, 255)
  pdf.text('CRYPTO ASTROLOGY REPORT', pageWidth / 2, yPos, { align: 'center' })
  
  yPos += 15
  pdf.setFontSize(10)
  pdf.setTextColor(150, 150, 150)
  pdf.text('Cyber-Taoism Fortune Analysis', pageWidth / 2, yPos, { align: 'center' })
  
  yPos += 20
  pdf.setDrawColor(0, 240, 255)
  pdf.line(margin, yPos, pageWidth - margin, yPos)
  
  yPos += 15
  pdf.setFontSize(16)
  pdf.setTextColor(0, 0, 0)
  pdf.text('Token: ' + result.tokenName, margin, yPos)
  
  yPos += 10
  pdf.setFontSize(8)
  pdf.setTextColor(100, 100, 100)
  pdf.text('Contract: ' + result.contractAddress, margin, yPos)
  
  yPos += 10
  pdf.text('Genesis: ' + result.genesisDate.toLocaleString('zh-CN'), margin, yPos)
  
  yPos += 20
  pdf.setFontSize(14)
  pdf.setTextColor(188, 19, 254)
  pdf.text('CORE METRICS', margin, yPos)
  
  yPos += 10
  pdf.setFontSize(12)
  pdf.setTextColor(0, 0, 0)
  pdf.text('Fortune Score: ' + result.fortuneScore + '/100', margin + 5, yPos)
  
  yPos += 8
  pdf.text('Risk Level: ' + result.riskLevel, margin + 5, yPos)
  
  yPos += 8
  pdf.text('Investment Advice: ' + result.investmentAdvice, margin + 5, yPos)
  
  yPos += 15
  pdf.setFontSize(14)
  pdf.setTextColor(188, 19, 254)
  pdf.text('ZIWEI ANALYSIS', margin, yPos)
  
  yPos += 10
  pdf.setFontSize(11)
  pdf.setTextColor(0, 0, 0)
  pdf.text('Life Palace Star: ' + result.ziwei.lifePalaceStar, margin + 5, yPos)
  
  yPos += 8
  pdf.text('Wealth Palace Star: ' + result.ziwei.wealthPalaceStar, margin + 5, yPos)
  
  yPos += 10
  pdf.setFontSize(10)
  const interpretationLines = pdf.splitTextToSize(result.ziwei.interpretation, pageWidth - 2 * margin - 10)
  pdf.text(interpretationLines, margin + 5, yPos)
  yPos += interpretationLines.length * 6
  
  yPos += 8
  pdf.text('Lucky Color: ' + result.ziwei.luckyColor, margin + 5, yPos)
  
  yPos += 8
  pdf.text('Lucky Number: ' + result.ziwei.luckyNumber, margin + 5, yPos)
  
  yPos += 15
  pdf.setFontSize(14)
  pdf.setTextColor(188, 19, 254)
  pdf.text('WESTERN ASTROLOGY', margin, yPos)
  
  yPos += 10
  pdf.setFontSize(11)
  pdf.setTextColor(0, 0, 0)
  pdf.text('Sun Sign: ' + result.western.sunSign, margin + 5, yPos)
  
  yPos += 8
  pdf.text('Market Sentiment: ' + result.western.marketSentiment, margin + 5, yPos)
  
  yPos += 10
  pdf.setFontSize(10)
  const aspectLines = pdf.splitTextToSize(result.western.aspectInfluence, pageWidth - 2 * margin - 10)
  pdf.text(aspectLines, margin + 5, yPos)
  yPos += aspectLines.length * 6
  
  yPos += 20
  pdf.setDrawColor(0, 240, 255)
  pdf.line(margin, yPos, pageWidth - margin, yPos)
  
  yPos += 10
  pdf.setFontSize(8)
  pdf.setTextColor(255, 42, 42)
  const disclaimer = 'This report is for entertainment purposes only. Not financial advice.'
  pdf.text(disclaimer, pageWidth / 2, yPos, { align: 'center' })
  
  yPos += 6
  pdf.setTextColor(150, 150, 150)
  pdf.text('Generated by Crypto Astrology | Cyber-Taoism Analysis System', pageWidth / 2, yPos, { align: 'center' })
  
  pdf.save(result.tokenName + '_fortune_report.pdf')
}
