import jsPDF from 'jspdf'
import { FortuneResult } from '../types'

export function generatePDF(result: FortuneResult) {
  const pdf = new jsPDF()

  const pageWidth = pdf.internal.pageSize.getWidth()
  const margin = 20
  let yPos = 20

  // Title
  pdf.setFontSize(24)
  pdf.setTextColor(15, 23, 42) // Slate 900
  pdf.text('Crypto Astrology Report', pageWidth / 2, yPos, { align: 'center' })

  yPos += 10
  pdf.setFontSize(10)
  pdf.setTextColor(100, 116, 139) // Slate 500
  pdf.text('On-chain Destiny Analysis', pageWidth / 2, yPos, { align: 'center' })

  yPos += 20
  pdf.setDrawColor(99, 102, 241) // Indigo 500
  pdf.line(margin, yPos, pageWidth - margin, yPos)

  yPos += 15
  pdf.setFontSize(14)
  pdf.setTextColor(15, 23, 42)
  pdf.text(result.tokenName, margin, yPos)

  yPos += 8
  pdf.setFontSize(8)
  pdf.setTextColor(100, 116, 139)
  pdf.text(result.contractAddress, margin, yPos)

  yPos += 6
  pdf.text('Genesis: ' + result.genesisDate.toLocaleString(), margin, yPos)

  yPos += 20
  pdf.setFontSize(12)
  pdf.setTextColor(99, 102, 241) // Indigo 500
  pdf.text('CORE ANALYSIS', margin, yPos)

  yPos += 10
  pdf.setFontSize(11)
  pdf.setTextColor(15, 23, 42)
  pdf.text('Fortune Score: ' + result.fortuneScore + '/100', margin, yPos)

  yPos += 8
  pdf.text('Risk Level: ' + result.riskLevel, margin, yPos)

  yPos += 8
  pdf.text('Verdict: ' + result.investmentAdvice, margin, yPos)

  yPos += 15
  pdf.setFontSize(12)
  pdf.setTextColor(99, 102, 241)
  pdf.text('EASTERN ASTROLOGY (Ziwei Dou Shu)', margin, yPos)

  yPos += 10
  pdf.setFontSize(10)
  pdf.setTextColor(15, 23, 42)
  pdf.text('Life Star: ' + result.ziwei.lifePalaceStar, margin, yPos)

  yPos += 6
  pdf.text('Wealth Star: ' + result.ziwei.wealthPalaceStar, margin, yPos)

  yPos += 8
  pdf.setFontSize(9)
  pdf.setTextColor(71, 85, 105) // Slate 600
  const interpretationLines = pdf.splitTextToSize(result.ziwei.interpretation, pageWidth - 2 * margin)
  pdf.text(interpretationLines, margin, yPos)
  yPos += interpretationLines.length * 5

  yPos += 8
  pdf.text('Lucky Color: ' + result.ziwei.luckyColor, margin, yPos)
  pdf.text('Lucky Number: ' + result.ziwei.luckyNumber, margin + 80, yPos)

  yPos += 20
  pdf.setDrawColor(226, 232, 240) // Slate 200
  pdf.line(margin, yPos, pageWidth - margin, yPos)

  yPos += 10
  pdf.setFontSize(8)
  pdf.setTextColor(148, 163, 184) // Slate 400
  const disclaimer = 'For entertainment purposes only. Not financial advice.'
  pdf.text(disclaimer, pageWidth / 2, yPos, { align: 'center' })

  yPos += 5
  pdf.text('Generated by Crypto Astrology', pageWidth / 2, yPos, { align: 'center' })

  pdf.save(result.tokenName + '_fortune_report.pdf')
}
